#!/bin/sh

set -e

echo "[$(date)] Executing SQL file: $1"

mysql -u "$TEST_USER" -h "$TEST_HOST" -P "$TEST_PORT" \
  --password="$TEST_PASSWORD" --database="$TEST_DATABASE" \
  --default-character-set utf8mb4 < "$1"
