language: go
dist: bionic

go:
  - 1.13.x

install:
  - sh install.sh

script:
  - make check
  - make test WITH_RACE=1
  - make integration_test

after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - mysql

if: branch = master OR branch =~ /^release-/